version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKER_FILE}
    container_name: ${DOCKER_NAME}
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - ${DOCKER_PORT}:3000
